require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Forum::PostsController do

  # This should return the minimal set of attributes required to create a valid
  # Forum::Post. As you add validations to Forum::Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { body: "Lorem ipsum.\nAnd another row." } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Forum::PostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all forum_posts as @forum_posts" do
      post = Forum::Post.create! valid_attributes
      get :index, {}, valid_session
      assigns(:forum_posts).should eq([post])
    end
  end

  describe "GET show" do
    it "assigns the requested forum_post as @forum_post" do
      post = Forum::Post.create! valid_attributes
      get :show, {:id => post.to_param}, valid_session
      assigns(:forum_post).should eq(post)
    end
  end

  describe "GET new" do
    it "assigns a new forum_post as @forum_post" do
      get :new, {}, valid_session
      assigns(:forum_post).should be_a_new(Forum::Post)
    end
  end

  describe "GET edit" do
    it "assigns the requested forum_post as @forum_post" do
      post = Forum::Post.create! valid_attributes
      get :edit, {:id => post.to_param}, valid_session
      assigns(:forum_post).should eq(post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Forum::Post" do
        expect {
          post :create, {:forum_post => valid_attributes}, valid_session
        }.to change(Forum::Post, :count).by(1)
      end

      it "assigns a newly created forum_post as @forum_post" do
        post :create, {:forum_post => valid_attributes}, valid_session
        assigns(:forum_post).should be_a(Forum::Post)
        assigns(:forum_post).should be_persisted
      end

      it "redirects to the created forum_post" do
        post :create, {:forum_post => valid_attributes}, valid_session
        response.should redirect_to(Forum::Post.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved forum_post as @forum_post" do
        # Trigger the behavior that occurs when invalid params are submitted
        Forum::Post.any_instance.stub(:save).and_return(false)
        post :create, {:forum_post => { "topic" => "invalid value" }}, valid_session
        assigns(:forum_post).should be_a_new(Forum::Post)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Forum::Post.any_instance.stub(:save).and_return(false)
        post :create, {:forum_post => { "topic" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested forum_post" do
        post = Forum::Post.create! valid_attributes
        # Assuming there are no other forum_posts in the database, this
        # specifies that the Forum::Post created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Forum::Post.any_instance.should_receive(:update).with({ "body" => "New data" })
        put :update, {:id => post.to_param, :forum_post => { "body" => "New data" }}, valid_session
      end

      it "assigns the requested forum_post as @forum_post" do
        post = Forum::Post.create! valid_attributes
        put :update, {:id => post.to_param, :forum_post => valid_attributes}, valid_session
        assigns(:forum_post).should eq(post)
      end

      it "redirects to the forum_post" do
        post = Forum::Post.create! valid_attributes
        put :update, {:id => post.to_param, :forum_post => valid_attributes}, valid_session
        response.should redirect_to(post)
      end
    end

    describe "with invalid params" do
      it "assigns the forum_post as @forum_post" do
        post = Forum::Post.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Forum::Post.any_instance.stub(:save).and_return(false)
        put :update, {:id => post.to_param, :forum_post => { "body" => "12" }}, valid_session
        assigns(:forum_post).should eq(post)
      end

      it "re-renders the 'edit' template" do
        post = Forum::Post.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Forum::Post.any_instance.stub(:save).and_return(false)
        put :update, {:id => post.to_param, :forum_post => { "body" => "12" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested forum_post" do
      post = Forum::Post.create! valid_attributes
      expect {
        delete :destroy, {:id => post.to_param}, valid_session
      }.to change(Forum::Post, :count).by(-1)
    end

    it "redirects to the forum_posts list" do
      post = Forum::Post.create! valid_attributes
      delete :destroy, {:id => post.to_param}, valid_session
      response.should redirect_to(forum_posts_url)
    end
  end

end
